# Generated by Django 3.0.5 on 2020-04-10 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal_user',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('otp', models.CharField(default=80611, max_length=5)),
                ('otp_generated', models.TextField(default='2020-04-11 00:06:50')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portal_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Portal_user')),
            ],
        ),
    ]
