# Generated by Django 3.0.5 on 2020-04-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_user',
            name='otp',
            field=models.CharField(default=36786, max_length=5),
        ),
        migrations.AlterField(
            model_name='portal_user',
            name='otp_generated',
            field=models.TextField(default='2020-04-11 00:48:40'),
        ),
    ]
