# Generated by Django 3.0.5 on 2020-04-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200411_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_user',
            name='otp_generated',
            field=models.TextField(default='2020-04-12 21:11:39'),
        ),
    ]
