# Generated by Django 3.0.5 on 2020-04-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20200412_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_user',
            name='otp_generated',
            field=models.TextField(),
        ),
    ]
