# Generated by Django 3.0.5 on 2020-04-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_official', '0004_auto_20200429_1506'),
        ('portal', '0011_auto_20200412_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal_user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=32, null=True)),
                ('lname', models.CharField(max_length=32, null=True)),
                ('email', models.CharField(max_length=32, null=True)),
                ('altno', models.CharField(max_length=32, null=True)),
                ('address', models.CharField(max_length=32, null=True)),
                ('place', models.CharField(max_length=32, null=True)),
                ('city', models.CharField(max_length=32, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('localbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_athorities_list')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Portal_user')),
            ],
        ),
        migrations.DeleteModel(
            name='Portal_profile',
        ),
    ]
