# Generated by Django 3.0.5 on 2020-04-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_official', '0004_auto_20200429_1506'),
        ('portal', '0012_auto_20200429_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=32)),
                ('item_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='food_ordering',
            fields=[
                ('item_order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_count', models.IntegerField()),
                ('order_date', models.TextField()),
                ('delivery_loc', models.CharField(max_length=32)),
                ('total_price', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.food_item')),
                ('localbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_athorities_list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Portal_user_profile')),
            ],
        ),
    ]
