# Generated by Django 3.0.5 on 2020-04-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_official', '0004_auto_20200429_1506'),
        ('portal', '0013_food_item_food_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item',
            name='item_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_item',
            name='item_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_item',
            name='localbody',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_athorities_list'),
        ),
        migrations.AlterField(
            model_name='food_item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food_ordering',
            name='item_order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food_ordering',
            name='localbody',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_athorities_list'),
        ),
        migrations.AlterField(
            model_name='food_ordering',
            name='order_date',
            field=models.TextField(null=True),
        ),
    ]
