# Generated by Django 3.0.5 on 2020-05-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_official', '0004_auto_20200429_1506'),
        ('portal', '0015_food_item_item_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.TextField(null=True)),
                ('total_price', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='food_orders_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qty', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.food_item')),
            ],
        ),
        migrations.DeleteModel(
            name='food_ordering',
        ),
        migrations.AddField(
            model_name='food_orders',
            name='items_ordered',
            field=models.ManyToManyField(to='portal.food_orders_list'),
        ),
        migrations.AddField(
            model_name='food_orders',
            name='localbody',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_athorities_list'),
        ),
        migrations.AddField(
            model_name='food_orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Portal_user_profile'),
        ),
    ]
