# Generated by Django 3.0.5 on 2020-05-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20200502_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_orders_list',
            name='customer_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_orders_list',
            name='item_date',
            field=models.TextField(null=True),
        ),
    ]
