# Generated by Django 3.0.5 on 2020-05-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20200502_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_order_list',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='food_order',
            name='uid',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='food_order_list',
            name='uid',
            field=models.TextField(default='0'),
        ),
    ]
