# Generated by Django 3.0.5 on 2020-05-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20200502_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_item_list_in_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qty', models.IntegerField()),
                ('item_date', models.TextField(null=True)),
                ('uid', models.TextField(default='0')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.food_item')),
            ],
        ),
        migrations.DeleteModel(
            name='food_order_list',
        ),
        migrations.AlterField(
            model_name='food_order',
            name='items_ordered',
            field=models.ManyToManyField(to='portal.food_item_list_in_orders'),
        ),
    ]
