# Generated by Django 3.0.5 on 2020-05-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20200502_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item_list_in_orders',
            name='user',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
