# Generated by Django 3.0.5 on 2020-05-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_food_item_list_in_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_order',
            name='items_ordered',
        ),
    ]
