# Generated by Django 3.0.5 on 2020-05-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_official', '0004_auto_20200429_1506'),
        ('portal', '0022_auto_20200502_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='foods_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.TextField(null=True)),
                ('total_price', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('uid', models.TextField(default='0')),
                ('items_ordered', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.food_item_list_in_orders')),
                ('localbody', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_athorities_list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Portal_user_profile')),
            ],
        ),
        migrations.DeleteModel(
            name='food_order',
        ),
    ]
