# Generated by Django 3.0.5 on 2020-05-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20200502_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods_order',
            name='items_ordered',
        ),
    ]
