# Generated by Django 3.0.5 on 2020-05-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_official', '0004_auto_20200429_1506'),
        ('portal', '0024_remove_foods_order_items_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item_list_in_orders',
            name='localbody',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_athorities_list'),
        ),
    ]
