# Generated by Django 2.2.6 on 2020-05-21 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_official', '0004_auto_20200429_1506'),
        ('portal', '0027_test_result_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_order',
            fields=[
                ('med_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.TextField(null=True)),
                ('total_price', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('uid', models.TextField(default='0')),
                ('localbody', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_athorities_list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Portal_user_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_list',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=32)),
                ('medicine_price', models.FloatField()),
                ('medicine_qty', models.IntegerField(default=0)),
                ('localbody', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_athorities_list')),
            ],
        ),
        migrations.CreateModel(
            name='medicine_item_list_in_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_qty', models.IntegerField()),
                ('order_date', models.TextField(null=True)),
                ('uid', models.TextField(default='0')),
                ('user', models.CharField(default='0', max_length=10)),
                ('localbody', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_athorities_list')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.food_item')),
            ],
        ),
    ]
