# Generated by Django 2.2.6 on 2020-05-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_medicine_item_list_in_orders_medicine_list_medicine_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine_item_list_in_orders',
            name='localbody',
        ),
        migrations.RemoveField(
            model_name='medicine_item_list_in_orders',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='medicine_item_list_in_orders',
            name='user',
        ),
        migrations.AddField(
            model_name='medicine_list',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
