# Generated by Django 3.0.5 on 2020-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global_variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(max_length=50)),
                ('var_type', models.CharField(choices=[('district', 'District'), ('state', 'State'), ('localbody_type', 'State')], max_length=50)),
                ('var_key', models.CharField(default='***', max_length=50)),
            ],
        ),
    ]
