# Generated by Django 3.0.5 on 2020-04-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_variable',
            name='var_type',
            field=models.CharField(choices=[('district', 'District'), ('state', 'State'), ('localbody_type', 'Localbody Type')], max_length=50),
        ),
    ]
