# Generated by Django 3.0.5 on 2020-04-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0002_auto_20200412_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global_variable',
            name='var_type',
        ),
        migrations.AddField(
            model_name='global_variable',
            name='var_data',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='global_variable',
            name='var_name',
            field=models.CharField(choices=[('district', 'District'), ('state', 'State'), ('localbody_type', 'Localbody Type')], max_length=50),
        ),
    ]
