# Generated by Django 3.0.5 on 2020-04-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='official_user',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=64)),
                ('designation', models.CharField(max_length=32)),
                ('contact_no', models.CharField(max_length=10)),
                ('localbody_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='official_athorities_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localbody_name', models.CharField(max_length=40)),
                ('localbody_type', models.CharField(max_length=32)),
                ('localbody_district', models.CharField(max_length=32)),
                ('localbody_state', models.CharField(max_length=32)),
                ('localbody_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_official.official_user')),
            ],
        ),
    ]
