# Generated by Django 3.0.5 on 2020-04-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_official', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_user',
            name='contact_person',
            field=models.CharField(default=0.0, max_length=32),
            preserve_default=False,
        ),
    ]
