# Generated by Django 3.0.5 on 2020-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_official', '0003_official_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official_user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
